### ISSUE TITLE
No Content Object definition found at TypoScript object path "tt_content.list.20.campuseventsfrontend_event"

### ISSUE THREAD

**Issue by dennismetz** [BrainAppeal/campus_events_frontend#4]
TYPO3 11.5.30
CampusEventsConnector 4.0.0
CampusEventsConvert2News 4.0.0
CampusEventsFrontend 4.0.0
PHP 8.0.x

After upgrading from 3.x to 4.x, there is now the following error in the frontend:
No Content Object definition found at TypoScript object path "tt_content.list.20.campuseventsfrontend_event"

**Comment by bahammes** [comment]
Hello,

since [TYPO3 12 does not support switchableControllerActions](https://docs.typo3.org/c/typo3/cms-core/main/en-us/Changelog/10.3/Deprecation-89463-SwitchableControllerActions.html) in FlexForms any more, we migrated the plugin to two new CType's (campuseventsfrontend_eventlist, campuseventsfrontend_eventshow).

There is an upgrade wizard for migrating existing content elements to the new content types:
`./vendor/bin/typo3 upgrade:run txCampusEventsFrontendPluginUpdater`

Nevertheless we have re-added the TypoScript for the old plugin in [release 4.0.1](https://github.com/BrainAppeal/campus_events_frontend/releases/tag/4.0.1), so it will not cause an exception any more.

**Comment by dennismetz** [comment]
Ah, I hadn't seen that, thanks for pointing it out!

I guess due to the change the TypoScript doesn't work for "plugin.tx_campuseventsfrontend_event.view" anymore... 

How can I overwrite the templates now?

**Comment by bahammes** [comment]
The TypoScript setup was still only defined for the old plugin (`plugin.tx_campuseventsfrontend_event.`), so the configuration was not used for all plugins.

We have released version 4.0.2 were the namespace of the TypoScript-Setup has been changed to `plugin.tx_campuseventsfrontend.`, so the setup will be used in all plugins of the extension.

If you have only changed the TypoScript constants, you don't have to change anything after the update for it to work again.

If you have changed the TypoScript setup, you have to change your customized TypoScript `plugin.tx_campuseventsfrontend_event.` to `plugin.tx_campuseventsfrontend.`

**Comment by dennismetz** [comment]
Great, thanks for the quick adjustment, now everything seems to work again.
